### ISSUE TITLE
How to get deeplink data when get notification

### ISSUE THREAD

**Issue by sirius2013** [mobiquity-networks/mnnotifications-plugin-cordova#1]
Hi Team.
I am working with this plugin for cordova app.
I have already all information with this link.
https://panel.mobiquitynetworks.com

I know we can send deeplink notification. I want to get data of deeplink notification on the app when get notification. (Like push notification callback)

Is this possible?

**Comment by sirius2013** [comment]
https://github.com/phonegap-build/PushPlugin/blob/a172e19/README.md
Push Notification has 
// iOS
function onNotificationAPN (event) {
}
// Android and Amazon Fire OS
function onNotification(e) {
}

so app can get data from notification I think.

Is there any API like this in this plugin?
I really need that.

**Comment by dnapolitano** [comment]
The SDK technically uses a local (not a push) notification when it is supplied a redirect URL (whether web-based or custom, aka “deep link”). The notification is presented using a standard UIView dialog. 

The local notification support is built into the notifications SDK and requires no additional implementation by you once you’ve successfully integrated that SDK. I think you’re already aware of this: I see that you have sent test notifications as recently as Saturday., and returned click-through events just over a week ago. So it looks as if all should be fine with your local notifications—but are you having a problem with them?

In either event, the Mobiquity Networks SDK does not perform push notifications at all. Visually, local notifications look the same to the app user, but we only send local notifications. 

Whether using the SDK natively or via the PhoneGap plug-in, if you wish to use push technology, you would need some other API. It’s outside our scope. 

I hope this is helpful, even though this is probably not what you’d hoped we could offer you. Thanks very much.

Sincerely,

Dan Napolitano
VP Client Services & Product Operations
Mobiquity Networks
(c) +1 917-270-4340
(e) dan@mobiquitynetworks.com

Confidentiality Note: This email may contain confidential and/or private information. If you received this email in error please delete and notify sender.




On Mar 10, 2016, at 1:29 AM, MobileWebPro <notifications@github.com> wrote:

https://github.com/phonegap-build/PushPlugin/blob/a172e19/README.md <https://github.com/phonegap-build/PushPlugin/blob/a172e19/README.md>
Push Notification has 
// iOS
function onNotificationAPN (event) {
}
// Android and Amazon Fire OS
function onNotification(e) {
}

so app can get data from notification I think.

Is there any API like this in this plugin?
I really need that.

**Comment by sirius2013** [comment]
Thank you for your answer.

so is there any handler to work for this notification?

**Comment by sirius2013** [comment]
I mean I want to contain some information in  the deeplink using https://panel.mobiquitynetworks.com.

and want to get that information from notification when get deeplink notify within our app?

Is this possible?
Thank you

**Comment by dnapolitano** [comment]
You mean, for instance, campaign tracking information?

if so, the answer is yes. You can pass back both some standard and customized variables as part of the notification body or the URL itself.

Standard values include: 
venue.name
venue.city
campaign.name
campaign.id
device.idFA
These can help you perform targeted marketing/tracking.

Also, any of the optional custom values you pass back (let me know if you need further details) can be incorporated, too.

If this wasn’t what you meant, please clarify and we’ll do our best to get you the answer you need.

Thanks!

Sincerely,

Dan Napolitano
VP Client Services & Product Operations
Mobiquity Networks
(c) +1 917-270-4340
(e) dan@mobiquitynetworks.com

Confidentiality Note: This email may contain confidential and/or private information. If you received this email in error please delete and notify sender.




On Mar 10, 2016, at 9:20 AM, MobileWebPro <notifications@github.com> wrote:

I mean I want to contain some information in the deeplink using https://panel.mobiquitynetworks.com <https://panel.mobiquitynetworks.com/>.

and want to get that information from notification when get deeplink notify within our app?

Is this possible?
Thank you

**Comment by sirius2013** [comment]
Well, I want to know is there any handler about notification receive in this plugin.
so I saw this function.
Mobiquity.NotificationManager.startMonitoring(successCallback, failureCallback, user, stats)
successCallback is handler?

actually when I launch app, I got this successCallback first even though I didn't connect any Beacon device.

**Comment by dnapolitano** [comment]
Yes, that’s probably a correct result, because it’s starting the SDK and might simply be ensuring it can connect to the mobile API—although I’d need to double check that specific result for you in order to be certain.

You can see the callbacks to the mobile API if you monitor via proxy. There is a particular callback for local notifications being displayed, yes. There’s also a callback to the server if the user clicks. 

These are not callbacks, though, that you can monitor apart from the SDK or repurpose. They’re essentially black-box, and the results of them are displayed in the panel. 

I hope this is helpful information, but I’m concerned that I don’t yet quite understand how to help you do something you’re trying to do, because I’m not 100% clear yet on what you’re attempting to do. I apologize if I have overlooked something, but would you please clarify what you’re trying to do?

Thank you.

Sincerely,

Dan Napolitano
VP Client Services & Product Operations
Mobiquity Networks
(c) +1 917-270-4340
(e) dan@mobiquitynetworks.com

Confidentiality Note: This email may contain confidential and/or private information. If you received this email in error please delete and notify sender.




On Mar 10, 2016, at 9:37 AM, MobileWebPro <notifications@github.com> wrote:

Well, I want to know is there any handler about notification receive in this plugin.
so I saw this function.
Mobiquity.NotificationManager.startMonitoring(successCallback, failureCallback, user, stats)
successCallback is handler?

actually when I launch app, I got this successCallback first even though I didn't connect any Beacon device.

**Comment by sirius2013** [comment]
here is one I want to do.
I want to send some variable (e.g. "hello" word ) on https://panel.mobiquitynetworks.com to my app.

if send "hello" with notification, I want to get that word "hello" within the app.

is this possible? If then, what is handler for that?

**Comment by dnapolitano** [comment]
Thanks.

So the SDK can only control itself, not the app in any way. The content configured in the SDK can only determine what the user sees in the local notification dialog and specify what referral link the user sees, whether the referral is a web URL or a deep link. 

You can use placeholder variables to send a user to a customized referral destination, possibly even one that responds to the content of the referral. So, for instance, let’s say that you are passing, as a custom variable, the user’s first name and IDFA. The landing page for the referral link might be configured to say:

"Hello {first name]. Welcome to {venue.name}. We see you like {interests}, and so here are some custom deals for you.”

The first name and the venue would just be plugged in and passed along by the SDK. The venue is a standard variable, and first name would be one you created and passed back through the SDK.

Based upon your marketing intelligence about the user’s IDFA, you would have a lookup on your back end correlating that IDFA to previously captured preferences. You would cross reference those against your currently available offers, and then you would populate the relevant offers.

You could even capture an HTML page that does this inside a web control so that the user doesn’t leave your app. Something a bit harder: you could write your app to consume information like this and respond the way the web page would, but now the entire user experience would be a native-app experience.

However, you can’t directly use the SDK to inject any content into the app itself. The SDK can only control the notification content and the referral link. Placeholder variables can be used to customize the message, the referral link, or both—but what happens as a result of those is outside the control of the SDK.

Are we getting closer to answering your question helpfully? Thank you again.

Sincerely,

Dan Napolitano
VP Client Services & Product Operations
Mobiquity Networks
(c) +1 917-270-4340
(e) dan@mobiquitynetworks.com

Confidentiality Note: This email may contain confidential and/or private information. If you received this email in error please delete and notify sender.




On Mar 10, 2016, at 10:10 AM, MobileWebPro <notifications@github.com> wrote:

here is one I want to do.
I want to send some variable (e.g. "hello" word ) on https://panel.mobiquitynetworks.com <https://panel.mobiquitynetworks.com/> to my app.

if send "hello" with notification, I want to get that word "hello" within the app.

is this possible? If then, what is handler for that?

**Comment by sirius2013** [comment]
Thank you for your message.

very sorry, I didn't get answer. 

Is there any this cordova plugin javascript function to implement this?

In my understanding, if we set deeplink information for beacon device, when detect that device within the app, app can get that deeplink information and "hello" word in that information?
is this possible?

**Comment by dnapolitano** [comment]
Please note: specific beacon (device) information isn’t passed back to the app. The app can pull back, as a program object, the name of the venue and the nearby points of interest. I’m not sure whether or how this affects your project. I hope not much at all; instead of looking for a device ID to trigger your next step, you’d have to set your trigger according to “near to” information, such as the user is near The Gap, or Macy’s, or AMC Theaters, etc. 

I apologize, too, because I’m definitely not an expert on Cordova. I know enough about our plug-in to support it in that context, but I’m not qualified to advise you on other plug-ins that might be available or even what JavaScript Apple will or will not allow to be run on the fly as part of the app. I suspect you know that Apple frowns on real-time execution of new code, especially external, and especially if the transport is not secure. But I really can’t tell you how to solve this problem using another third-party’s tools. 

Sincerely,

Dan Napolitano
VP Client Services & Product Operations
Mobiquity Networks
(c) +1 917-270-4340
(e) dan@mobiquitynetworks.com

Confidentiality Note: This email may contain confidential and/or private information. If you received this email in error please delete and notify sender.




On Mar 10, 2016, at 10:45 AM, MobileWebPro <notifications@github.com> wrote:

Thank you for your message.

very sorry, I didn't get answer.

Is there any this cordova plugin javascript function to implement this?

In my understanding, if we set deeplink information for beacon device, when detect that device within the app, app can get that deeplink information and "hello" word in that information?
is this possible?

**Comment by sirius2013** [comment]
Well, I just debugged the native code, but callback is not working for cordova app.

for example. I changed the status of Bluetooth of device, MNNNotificationsPlugin.m showed 
"didChangeBluetoothState:5 => BluetoothSatePoweredOn", but callback to cordova plugin js is not working, so I can't detect status of Bluetooth in the cordova app.

This is example issue of this plugin.
Besides these, I don't think other callback works fine also.

Did you check this plugin before launch?
I attached the screenshot for reference.
![image](https://cloud.githubusercontent.com/assets/5020713/13886664/f4998ebe-ed72-11e5-8b91-141965c30661.png)

Thank you

**Comment by sirius2013** [comment]
and do you think should I use other plugin to work with deeplink thing?

**Comment by dnapolitano** [comment]
We hope to have a look at the Bluetooth issue report for you soon.

In the interim, again, regarding deep links, the best we can do is to suggest a couple of options for managing your deep linking. Please have a look at:

https://github.com/EddyVerbruggen/Custom-URL-scheme <https://github.com/EddyVerbruggen/Custom-URL-scheme>

Our plug-in will also execute mycoolapp://coolapp.com?param1=hello&param2=5 <mycoolapp://coolapp.com?param1=hello&param2=5>. You could parse it out when you launch your app.

Sincerely,

Dan Napolitano
VP Client Services & Product Operations
Mobiquity Networks
(c) +1 917-270-4340
(e) dan@mobiquitynetworks.com

Confidentiality Note: This email may contain confidential and/or private information. If you received this email in error please delete and notify sender.




On Mar 18, 2016, at 1:38 PM, MobileWebPro <notifications@github.com> wrote:

and do you think should I use other plugin to work with deeplink thing?

**Comment by sirius2013** [comment]
Hello. we can use that plugin from email or web link.
but we can't use for deeplink because Mobiquity deeplink didn't pass URL to the app.

**Comment by sirius2013** [comment]
See below screenshots.

**Comment by sirius2013** [comment]
![image](https://cloud.githubusercontent.com/assets/5020713/14044215/ded3c7a6-f2c8-11e5-93f8-804f1a13cd9a.png)

**Comment by sirius2013** [comment]
![image](https://cloud.githubusercontent.com/assets/5020713/14044220/e9eebefc-f2c8-11e5-8c3f-cdad574e3a67.png)

**Comment by sirius2013** [comment]
![image](https://cloud.githubusercontent.com/assets/5020713/14044223/f1fea756-f2c8-11e5-856e-65aed1c8001a.png)

**Comment by dnapolitano** [comment]
So it looks like all is working fine now, yes? I’m seeing both campaigns delivered and clicked in the panel.

We are still pending analysis on the Bluetooth state issue. Sorry to keep you waiting, we’re just highly resource contended recently. 

Sincerely,

Dan Napolitano
VP Client Services & Product Operations
Mobiquity Networks
(c) +1 917-270-4340
(e) dan@mobiquitynetworks.com

Confidentiality Note: This email may contain confidential and/or private information. If you received this email in error please delete and notify sender.




On Mar 25, 2016, at 8:34 AM, MobileWebPro <notifications@github.com> wrote:

 <https://cloud.githubusercontent.com/assets/5020713/14044223/f1fea756-f2c8-11e5-856e-65aed1c8001a.png>

**Comment by sirius2013** [comment]
No. issue didn't solve.
I need to Deeplink content, No message! 
:(

Thanks

**Comment by dnapolitano** [comment]
Hi, apologies. I don’t yet understand the issue. So what I see according to the panel and screen caps is:

1) You can configure a notification in the panel with a deep link.
2) The notification is delivered to the phone.
3) The panel shows that the notification is being delivered.
4) When you click the notification, the panel shows it’s being clicked.

From there, I cannot tell whether the redirect is happening as you intend, but please bear in mind: the SDK only provides the redirect content. Actually consuming the redirect link and redirecting is an app-level function. If you’re clicking and not being redirected, that’s either an issue with the URI being malformed/invalid (which would result in no redirect) or an issue with the deep link code itself not working.

May I suggest that you try, for test purposes only, using a regular web link? Just set the address to http://www.yahoo.com <http://www.yahoo.com/> or some similar well-known URL. If that works, you’ve narrowed down your issue to deep link handling. 

Don’t forget, please, that due to iOS 9, if you wish to hand off general (non-HTTPS) content, you’ll need to update your app’s .plist App Transport Security Settings key (adding Allow Arbitrary Loads and specifying the Boolean Yes). 

You may also wish to double check that you’ve added couwalla:// as a string entry to your .plist’s LSApplicationQueriesSchemes key. Again, to support iOS 9.x, this has become a requirement. 

I hope this is helpful. Please let us know. 

Thanks. 

Sincerely,

Dan Napolitano
VP Client Services & Product Operations
Mobiquity Networks
(c) +1 917-270-4340
(e) dan@mobiquitynetworks.com

Confidentiality Note: This email may contain confidential and/or private information. If you received this email in error please delete and notify sender.




On Mar 25, 2016, at 10:09 AM, MobileWebPro <notifications@github.com> wrote:

No. issue didn't solve.
I need to Deeplink content, No message! 
:(

Thanks

**Comment by dnapolitano** [comment]
Sorry for the long lead time on response, I’ve just been very tied up.

Beginning with iOS 9, Apple by default requires referral payloads to be HTTPS, in order to prevent malicious redirects. There is a new key, App Transport Security, in your .plist. Apple is hoping that you will be redirecting to your site or other known sites that are all certified reliable and secure through HTTPS. 

Many apps will bring in third-party content that is not secured through HTTPS. In order to be able to do so, an app needs to update its .plist key App Transport Security settings as I described below.

Apple also changed its redirect policy beginning with iOS 9. In order for your app to use a deep link schema, you have to whitelist it in your .plist’s LSApplicationQueriesSchemes key. This includes linking to (and opening from your app) popular apps such as Instagram, Facebook, Twitter, etc. But it also includes your own deep link (your own app). 

Any deep link handler not listed in LSApplicationQueriesSchemes will silently fail. 

Please let me know if this clarification is helpful. 

Sincerely,

Dan Napolitano
VP Client Services & Product Operations
Mobiquity Networks
(c) +1 917-270-4340
(e) dan@mobiquitynetworks.com

Confidentiality Note: This email may contain confidential and/or private information. If you received this email in error please delete and notify sender.




On Mar 30, 2016, at 6:04 PM, MobileWebPro <notifications@github.com> wrote:

Hi
could you explain about this in detail?
Don’t forget, please, that due to iOS 9, if you wish to hand off general (non-HTTPS) content, you’ll need to update your app’s .plist App Transport Security Settings key (adding Allow Arbitrary Loads and specifying the Boolean Yes).
You may also wish to double check that you’ve added couwalla:// as a string entry to your .plist’s LSApplicationQueriesSchemes key. Again, to support iOS 9.x, this has become a requirement.
